
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)

interface _GlobalComponents {
      'Forging': typeof import("../../app/components/Forging.vue")['default']
    'GameCanvas': typeof import("../../app/components/GameCanvas.vue")['default']
    'GameInfo': typeof import("../../app/components/GameInfo.vue")['default']
    'Info': typeof import("../../app/components/Info.vue")['default']
    'Lobby': typeof import("../../app/components/Lobby.vue")['default']
    'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Upgrades': typeof import("../../app/components/Upgrades.vue")['default']
    'UColorModeAvatarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.d.vue")['default']
    'UColorModeAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue")['default']
    'UColorModeButtonDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.d.vue")['default']
    'UColorModeButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue")['default']
    'UColorModeImageDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.d.vue")['default']
    'UColorModeImage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue")['default']
    'UColorModeSelectDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.d.vue")['default']
    'UColorModeSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue")['default']
    'UColorModeSwitchDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.d.vue")['default']
    'UColorModeSwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue")['default']
    'UAccordionDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.d.vue")['default']
    'UAccordion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']
    'UAlertDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.d.vue")['default']
    'UAlert': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']
    'UAppDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.d.vue")['default']
    'UApp': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']
    'UAuthFormDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.d.vue")['default']
    'UAuthForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue")['default']
    'UAvatarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.d.vue")['default']
    'UAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']
    'UAvatarGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.d.vue")['default']
    'UAvatarGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']
    'UBadgeDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.d.vue")['default']
    'UBadge': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']
    'UBannerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.d.vue")['default']
    'UBanner': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue")['default']
    'UBlogPostDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.d.vue")['default']
    'UBlogPost': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue")['default']
    'UBlogPostsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.d.vue")['default']
    'UBlogPosts': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue")['default']
    'UBreadcrumbDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.d.vue")['default']
    'UBreadcrumb': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']
    'UButtonDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.d.vue")['default']
    'UButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']
    'UCalendarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.d.vue")['default']
    'UCalendar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']
    'UCardDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.d.vue")['default']
    'UCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']
    'UCarouselDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.d.vue")['default']
    'UCarousel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']
    'UChangelogVersionDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.d.vue")['default']
    'UChangelogVersion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue")['default']
    'UChangelogVersionsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.d.vue")['default']
    'UChangelogVersions': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue")['default']
    'UChatMessageDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.d.vue")['default']
    'UChatMessage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue")['default']
    'UChatMessagesDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.d.vue")['default']
    'UChatMessages': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue")['default']
    'UChatPaletteDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.d.vue")['default']
    'UChatPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue")['default']
    'UChatPromptDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.d.vue")['default']
    'UChatPrompt': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue")['default']
    'UChatPromptSubmitDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.d.vue")['default']
    'UChatPromptSubmit': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue")['default']
    'UCheckboxDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.d.vue")['default']
    'UCheckbox': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']
    'UCheckboxGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.d.vue")['default']
    'UCheckboxGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']
    'UChipDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.d.vue")['default']
    'UChip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']
    'UCollapsibleDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.d.vue")['default']
    'UCollapsible': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']
    'UColorPickerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.d.vue")['default']
    'UColorPicker': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']
    'UCommandPaletteDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.d.vue")['default']
    'UCommandPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']
    'UContainerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.d.vue")['default']
    'UContainer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']
    'UContextMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.d.vue")['default']
    'UContextMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']
    'UContextMenuContentDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.d.vue")['default']
    'UContextMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']
    'UDashboardGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.d.vue")['default']
    'UDashboardGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue")['default']
    'UDashboardNavbarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.d.vue")['default']
    'UDashboardNavbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue")['default']
    'UDashboardPanelDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.d.vue")['default']
    'UDashboardPanel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue")['default']
    'UDashboardResizeHandleDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.d.vue")['default']
    'UDashboardResizeHandle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue")['default']
    'UDashboardSearchDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.d.vue")['default']
    'UDashboardSearch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue")['default']
    'UDashboardSearchButtonDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.d.vue")['default']
    'UDashboardSearchButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue")['default']
    'UDashboardSidebarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.d.vue")['default']
    'UDashboardSidebar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue")['default']
    'UDashboardSidebarCollapseDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.d.vue")['default']
    'UDashboardSidebarCollapse': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue")['default']
    'UDashboardSidebarToggleDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.d.vue")['default']
    'UDashboardSidebarToggle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue")['default']
    'UDashboardToolbarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.d.vue")['default']
    'UDashboardToolbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue")['default']
    'UDrawerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.d.vue")['default']
    'UDrawer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']
    'UDropdownMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.d.vue")['default']
    'UDropdownMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']
    'UDropdownMenuContentDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.d.vue")['default']
    'UDropdownMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']
    'UErrorDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.d.vue")['default']
    'UError': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue")['default']
    'UFieldGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.d.vue")['default']
    'UFieldGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue")['default']
    'UFileUploadDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.d.vue")['default']
    'UFileUpload': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']
    'UFooterDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.d.vue")['default']
    'UFooter': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue")['default']
    'UFooterColumnsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.d.vue")['default']
    'UFooterColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue")['default']
    'UFormDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.d.vue")['default']
    'UForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']
    'UFormFieldDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.d.vue")['default']
    'UFormField': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']
    'UHeaderDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.d.vue")['default']
    'UHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue")['default']
    'UIconDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.d.vue")['default']
    'UIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']
    'UInputDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.d.vue")['default']
    'UInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']
    'UInputMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.d.vue")['default']
    'UInputMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']
    'UInputNumberDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.d.vue")['default']
    'UInputNumber': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']
    'UInputTagsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.d.vue")['default']
    'UInputTags': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']
    'UKbdDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.d.vue")['default']
    'UKbd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']
    'ULinkDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.d.vue")['default']
    'ULink': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']
    'ULinkBaseDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.d.vue")['default']
    'ULinkBase': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']
    'UMainDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.d.vue")['default']
    'UMain': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue")['default']
    'UMarqueeDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.d.vue")['default']
    'UMarquee': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue")['default']
    'UModalDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.d.vue")['default']
    'UModal': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']
    'UNavigationMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.d.vue")['default']
    'UNavigationMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']
    'UOverlayProviderDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.d.vue")['default']
    'UOverlayProvider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']
    'UPageDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.d.vue")['default']
    'UPage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue")['default']
    'UPageAnchorsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.d.vue")['default']
    'UPageAnchors': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue")['default']
    'UPageAsideDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.d.vue")['default']
    'UPageAside': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue")['default']
    'UPageBodyDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.d.vue")['default']
    'UPageBody': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue")['default']
    'UPageCTADVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.d.vue")['default']
    'UPageCTA': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue")['default']
    'UPageCardDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.d.vue")['default']
    'UPageCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue")['default']
    'UPageColumnsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.d.vue")['default']
    'UPageColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue")['default']
    'UPageFeatureDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.d.vue")['default']
    'UPageFeature': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue")['default']
    'UPageGridDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.d.vue")['default']
    'UPageGrid': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue")['default']
    'UPageHeaderDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.d.vue")['default']
    'UPageHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue")['default']
    'UPageHeroDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.d.vue")['default']
    'UPageHero': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue")['default']
    'UPageLinksDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.d.vue")['default']
    'UPageLinks': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue")['default']
    'UPageListDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.d.vue")['default']
    'UPageList': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue")['default']
    'UPageLogosDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.d.vue")['default']
    'UPageLogos': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue")['default']
    'UPageSectionDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.d.vue")['default']
    'UPageSection': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue")['default']
    'UPaginationDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.d.vue")['default']
    'UPagination': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']
    'UPinInputDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.d.vue")['default']
    'UPinInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']
    'UPopoverDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.d.vue")['default']
    'UPopover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']
    'UPricingPlanDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.d.vue")['default']
    'UPricingPlan': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue")['default']
    'UPricingPlansDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.d.vue")['default']
    'UPricingPlans': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue")['default']
    'UPricingTableDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.d.vue")['default']
    'UPricingTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue")['default']
    'UProgressDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.d.vue")['default']
    'UProgress': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']
    'URadioGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.d.vue")['default']
    'URadioGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']
    'USelectDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.d.vue")['default']
    'USelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']
    'USelectMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.d.vue")['default']
    'USelectMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']
    'USeparatorDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.d.vue")['default']
    'USeparator': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']
    'USkeletonDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.d.vue")['default']
    'USkeleton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']
    'USlideoverDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.d.vue")['default']
    'USlideover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']
    'USliderDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.d.vue")['default']
    'USlider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']
    'UStepperDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.d.vue")['default']
    'UStepper': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']
    'USwitchDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.d.vue")['default']
    'USwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']
    'UTableDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.d.vue")['default']
    'UTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue")['default']
    'UTabsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.d.vue")['default']
    'UTabs': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']
    'UTextareaDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.d.vue")['default']
    'UTextarea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']
    'UTimelineDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.d.vue")['default']
    'UTimeline': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']
    'UToastDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.d.vue")['default']
    'UToast': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']
    'UToasterDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.d.vue")['default']
    'UToaster': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']
    'UTooltipDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.d.vue")['default']
    'UTooltip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']
    'UTreeDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.d.vue")['default']
    'UTree': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']
    'UUserDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.d.vue")['default']
    'UUser': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue")['default']
    'ULocaleSelectDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.d.vue")['default']
    'ULocaleSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue")['default']
    'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
    'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyForging': LazyComponent<typeof import("../../app/components/Forging.vue")['default']>
    'LazyGameCanvas': LazyComponent<typeof import("../../app/components/GameCanvas.vue")['default']>
    'LazyGameInfo': LazyComponent<typeof import("../../app/components/GameInfo.vue")['default']>
    'LazyInfo': LazyComponent<typeof import("../../app/components/Info.vue")['default']>
    'LazyLobby': LazyComponent<typeof import("../../app/components/Lobby.vue")['default']>
    'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
    'LazyUpgrades': LazyComponent<typeof import("../../app/components/Upgrades.vue")['default']>
    'LazyUColorModeAvatarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.d.vue")['default']>
    'LazyUColorModeAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue")['default']>
    'LazyUColorModeButtonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.d.vue")['default']>
    'LazyUColorModeButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue")['default']>
    'LazyUColorModeImageDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.d.vue")['default']>
    'LazyUColorModeImage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue")['default']>
    'LazyUColorModeSelectDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.d.vue")['default']>
    'LazyUColorModeSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue")['default']>
    'LazyUColorModeSwitchDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.d.vue")['default']>
    'LazyUColorModeSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue")['default']>
    'LazyUAccordionDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.d.vue")['default']>
    'LazyUAccordion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']>
    'LazyUAlertDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.d.vue")['default']>
    'LazyUAlert': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']>
    'LazyUAppDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.d.vue")['default']>
    'LazyUApp': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']>
    'LazyUAuthFormDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.d.vue")['default']>
    'LazyUAuthForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue")['default']>
    'LazyUAvatarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.d.vue")['default']>
    'LazyUAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']>
    'LazyUAvatarGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.d.vue")['default']>
    'LazyUAvatarGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']>
    'LazyUBadgeDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.d.vue")['default']>
    'LazyUBadge': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']>
    'LazyUBannerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.d.vue")['default']>
    'LazyUBanner': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue")['default']>
    'LazyUBlogPostDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.d.vue")['default']>
    'LazyUBlogPost': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue")['default']>
    'LazyUBlogPostsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.d.vue")['default']>
    'LazyUBlogPosts': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue")['default']>
    'LazyUBreadcrumbDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.d.vue")['default']>
    'LazyUBreadcrumb': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']>
    'LazyUButtonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.d.vue")['default']>
    'LazyUButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']>
    'LazyUCalendarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.d.vue")['default']>
    'LazyUCalendar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']>
    'LazyUCardDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.d.vue")['default']>
    'LazyUCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']>
    'LazyUCarouselDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.d.vue")['default']>
    'LazyUCarousel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']>
    'LazyUChangelogVersionDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.d.vue")['default']>
    'LazyUChangelogVersion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue")['default']>
    'LazyUChangelogVersionsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.d.vue")['default']>
    'LazyUChangelogVersions': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue")['default']>
    'LazyUChatMessageDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.d.vue")['default']>
    'LazyUChatMessage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue")['default']>
    'LazyUChatMessagesDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.d.vue")['default']>
    'LazyUChatMessages': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue")['default']>
    'LazyUChatPaletteDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.d.vue")['default']>
    'LazyUChatPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue")['default']>
    'LazyUChatPromptDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.d.vue")['default']>
    'LazyUChatPrompt': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue")['default']>
    'LazyUChatPromptSubmitDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.d.vue")['default']>
    'LazyUChatPromptSubmit': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue")['default']>
    'LazyUCheckboxDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.d.vue")['default']>
    'LazyUCheckbox': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']>
    'LazyUCheckboxGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.d.vue")['default']>
    'LazyUCheckboxGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']>
    'LazyUChipDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.d.vue")['default']>
    'LazyUChip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']>
    'LazyUCollapsibleDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.d.vue")['default']>
    'LazyUCollapsible': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']>
    'LazyUColorPickerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.d.vue")['default']>
    'LazyUColorPicker': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']>
    'LazyUCommandPaletteDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.d.vue")['default']>
    'LazyUCommandPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']>
    'LazyUContainerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.d.vue")['default']>
    'LazyUContainer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']>
    'LazyUContextMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.d.vue")['default']>
    'LazyUContextMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']>
    'LazyUContextMenuContentDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.d.vue")['default']>
    'LazyUContextMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']>
    'LazyUDashboardGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.d.vue")['default']>
    'LazyUDashboardGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue")['default']>
    'LazyUDashboardNavbarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.d.vue")['default']>
    'LazyUDashboardNavbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue")['default']>
    'LazyUDashboardPanelDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.d.vue")['default']>
    'LazyUDashboardPanel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue")['default']>
    'LazyUDashboardResizeHandleDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.d.vue")['default']>
    'LazyUDashboardResizeHandle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue")['default']>
    'LazyUDashboardSearchDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.d.vue")['default']>
    'LazyUDashboardSearch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue")['default']>
    'LazyUDashboardSearchButtonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.d.vue")['default']>
    'LazyUDashboardSearchButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue")['default']>
    'LazyUDashboardSidebarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.d.vue")['default']>
    'LazyUDashboardSidebar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue")['default']>
    'LazyUDashboardSidebarCollapseDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.d.vue")['default']>
    'LazyUDashboardSidebarCollapse': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue")['default']>
    'LazyUDashboardSidebarToggleDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.d.vue")['default']>
    'LazyUDashboardSidebarToggle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue")['default']>
    'LazyUDashboardToolbarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.d.vue")['default']>
    'LazyUDashboardToolbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue")['default']>
    'LazyUDrawerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.d.vue")['default']>
    'LazyUDrawer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']>
    'LazyUDropdownMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.d.vue")['default']>
    'LazyUDropdownMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']>
    'LazyUDropdownMenuContentDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.d.vue")['default']>
    'LazyUDropdownMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']>
    'LazyUErrorDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.d.vue")['default']>
    'LazyUError': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue")['default']>
    'LazyUFieldGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.d.vue")['default']>
    'LazyUFieldGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue")['default']>
    'LazyUFileUploadDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.d.vue")['default']>
    'LazyUFileUpload': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']>
    'LazyUFooterDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.d.vue")['default']>
    'LazyUFooter': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue")['default']>
    'LazyUFooterColumnsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.d.vue")['default']>
    'LazyUFooterColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue")['default']>
    'LazyUFormDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.d.vue")['default']>
    'LazyUForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']>
    'LazyUFormFieldDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.d.vue")['default']>
    'LazyUFormField': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']>
    'LazyUHeaderDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.d.vue")['default']>
    'LazyUHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue")['default']>
    'LazyUIconDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.d.vue")['default']>
    'LazyUIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']>
    'LazyUInputDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.d.vue")['default']>
    'LazyUInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']>
    'LazyUInputMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.d.vue")['default']>
    'LazyUInputMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']>
    'LazyUInputNumberDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.d.vue")['default']>
    'LazyUInputNumber': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']>
    'LazyUInputTagsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.d.vue")['default']>
    'LazyUInputTags': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']>
    'LazyUKbdDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.d.vue")['default']>
    'LazyUKbd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']>
    'LazyULinkDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.d.vue")['default']>
    'LazyULink': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']>
    'LazyULinkBaseDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.d.vue")['default']>
    'LazyULinkBase': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']>
    'LazyUMainDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.d.vue")['default']>
    'LazyUMain': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue")['default']>
    'LazyUMarqueeDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.d.vue")['default']>
    'LazyUMarquee': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue")['default']>
    'LazyUModalDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.d.vue")['default']>
    'LazyUModal': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']>
    'LazyUNavigationMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.d.vue")['default']>
    'LazyUNavigationMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']>
    'LazyUOverlayProviderDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.d.vue")['default']>
    'LazyUOverlayProvider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']>
    'LazyUPageDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.d.vue")['default']>
    'LazyUPage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue")['default']>
    'LazyUPageAnchorsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.d.vue")['default']>
    'LazyUPageAnchors': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue")['default']>
    'LazyUPageAsideDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.d.vue")['default']>
    'LazyUPageAside': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue")['default']>
    'LazyUPageBodyDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.d.vue")['default']>
    'LazyUPageBody': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue")['default']>
    'LazyUPageCTADVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.d.vue")['default']>
    'LazyUPageCTA': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue")['default']>
    'LazyUPageCardDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.d.vue")['default']>
    'LazyUPageCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue")['default']>
    'LazyUPageColumnsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.d.vue")['default']>
    'LazyUPageColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue")['default']>
    'LazyUPageFeatureDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.d.vue")['default']>
    'LazyUPageFeature': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue")['default']>
    'LazyUPageGridDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.d.vue")['default']>
    'LazyUPageGrid': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue")['default']>
    'LazyUPageHeaderDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.d.vue")['default']>
    'LazyUPageHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue")['default']>
    'LazyUPageHeroDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.d.vue")['default']>
    'LazyUPageHero': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue")['default']>
    'LazyUPageLinksDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.d.vue")['default']>
    'LazyUPageLinks': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue")['default']>
    'LazyUPageListDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.d.vue")['default']>
    'LazyUPageList': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue")['default']>
    'LazyUPageLogosDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.d.vue")['default']>
    'LazyUPageLogos': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue")['default']>
    'LazyUPageSectionDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.d.vue")['default']>
    'LazyUPageSection': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue")['default']>
    'LazyUPaginationDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.d.vue")['default']>
    'LazyUPagination': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']>
    'LazyUPinInputDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.d.vue")['default']>
    'LazyUPinInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']>
    'LazyUPopoverDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.d.vue")['default']>
    'LazyUPopover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']>
    'LazyUPricingPlanDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.d.vue")['default']>
    'LazyUPricingPlan': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue")['default']>
    'LazyUPricingPlansDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.d.vue")['default']>
    'LazyUPricingPlans': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue")['default']>
    'LazyUPricingTableDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.d.vue")['default']>
    'LazyUPricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue")['default']>
    'LazyUProgressDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.d.vue")['default']>
    'LazyUProgress': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']>
    'LazyURadioGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.d.vue")['default']>
    'LazyURadioGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']>
    'LazyUSelectDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.d.vue")['default']>
    'LazyUSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']>
    'LazyUSelectMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.d.vue")['default']>
    'LazyUSelectMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']>
    'LazyUSeparatorDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.d.vue")['default']>
    'LazyUSeparator': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']>
    'LazyUSkeletonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.d.vue")['default']>
    'LazyUSkeleton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']>
    'LazyUSlideoverDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.d.vue")['default']>
    'LazyUSlideover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']>
    'LazyUSliderDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.d.vue")['default']>
    'LazyUSlider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']>
    'LazyUStepperDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.d.vue")['default']>
    'LazyUStepper': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']>
    'LazyUSwitchDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.d.vue")['default']>
    'LazyUSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']>
    'LazyUTableDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.d.vue")['default']>
    'LazyUTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue")['default']>
    'LazyUTabsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.d.vue")['default']>
    'LazyUTabs': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']>
    'LazyUTextareaDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.d.vue")['default']>
    'LazyUTextarea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']>
    'LazyUTimelineDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.d.vue")['default']>
    'LazyUTimeline': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']>
    'LazyUToastDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.d.vue")['default']>
    'LazyUToast': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']>
    'LazyUToasterDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.d.vue")['default']>
    'LazyUToaster': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']>
    'LazyUTooltipDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.d.vue")['default']>
    'LazyUTooltip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']>
    'LazyUTreeDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.d.vue")['default']>
    'LazyUTree': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']>
    'LazyUUserDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.d.vue")['default']>
    'LazyUUser': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue")['default']>
    'LazyULocaleSelectDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.d.vue")['default']>
    'LazyULocaleSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue")['default']>
    'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
    'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
    'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
    'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
    'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
    'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
    'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
    'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
    'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
    'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
    'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
    'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
    'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
    'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
    'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
    'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
    'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
    'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
    'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
    'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
    'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
    'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
